# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
    name = "Blog"
    pageRef = "posts"
    weight = 10

[[main]]
    name = "About"
    pageRef = "about"
    weight  = 20



[[main]]
    name = "Category"
    # pageRef = "categories"
    weight = 30
[[main]]
    name = "CTF"
    weight = 30
    parent = "Category"
    pageRef = "posts/CTF"
[[main]]
    name = "Malware"
    weight = 30
    parent = "Category"
    pageRef = "posts/malware-section"
[[main]]
    name = "Linux-kernel"
    weight = 30
    parent = "Category"
[[main]]
    name = "Game-hacking"
    weight = 30
    parent = "Category"
    pageRef = "posts/gamehack"
[[main]]
    name = "Pwn-exploit"
    pageRef = "posts/Pwn-exploit"
    weight = 30
    parent = "Category"
[[main]]
    name = "Tags"
    pageRef = "tags"
    weight = 40


[[main]]
    pre = "github"
    url = "https://github.com/sinkthemall"
    weight = 50

# [[main]]
#     pre = "x-twitter"
#     url = "https://x.com/d4rkn19ht_"
#     weight = 60


# [[main]]
#     name = "Test1"
#     weight= 30
# [[main]]
#     name = "Test2"
#     parent = "Test1"
#     weight = 30
# [[main]]
#     name = "Test3"
#     parent = "Test1"
#     weight = 30

# [[subnavigation]]
#   name = "An interesting topic"
#   pageRef = "tags/interesting-topic"
#   weight = 40

# [[subnavigation]]
#   name = "My Awesome Category"
#   pageRef = "categories/awesome"
#   weight = 50
#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
